spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/Literalura
spring.datasource.username=postgres
spring.datasource.password=02032025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
